include(CMakeParseArguments)

function(ProxyStubGenerator)
    # Thunder / ThunderInterfaces use:
    #   ProxyStubGenerator(
    #       NAMESPACE ...
    #       INPUT <headers...>
    #       OUTDIR <dir>
    #       INCLUDE_PATH <dirs...> (sometimes)
    #   )
    set(options "")
    set(oneValueArgs NAMESPACE OUTDIR)
    set(multiValueArgs INPUT INCLUDE_PATH)
    cmake_parse_arguments(PSG "${options}" "${oneValueArgs}" "${multiValueArgs}" ${ARGN})

    if(NOT PSG_OUTDIR)
        message(FATAL_ERROR "ProxyStubGenerator: OUTDIR is required")
    endif()

    file(MAKE_DIRECTORY "${PSG_OUTDIR}")

    # For now, ignore INPUT/INCLUDE_PATH and just generate a dummy COM stub.
    # Thunder's COM CMakeLists expects ProxyStubs_COM.cpp to exist.
    set(_outfile "${PSG_OUTDIR}/ProxyStubs_COM.cpp")

    if(NOT EXISTS "${_outfile}")
        message(STATUS "ProxyStubGenerator (dummy): creating ${_outfile}")
        file(WRITE "${_outfile}" "
            // Dummy COM proxy stubs.
            // Generated by local ProxyStubGenerator stub.
            //
            // COM RPC is effectively disabled in this build; this file only
            // exists to satisfy the build system.

            namespace Thunder {
            namespace ProxyStubs {
            // intentionally empty
            }
            }
        ")
    else()
        message(STATUS "ProxyStubGenerator (dummy): ${_outfile} already exists")
    endif()
endfunction()

