# Ultra-simple FindProxyStubGenerator.cmake for this Thunder layout
#
# We treat the directory that contains config_generator.py as the
# "ProxyStubGenerator" root, even though upstream calls it ConfigGenerator.
#
# Exposes:
#   ProxyStubGenerator_FOUND
#   ProxyStubGenerator_ROOT
#
# And defines a stub macro:
#   ProxyStubGenerator(NAMESPACE <ns> INPUT <headers...> OUTDIR <dir> INCLUDE_PATH <dirs...>)

message(STATUS ">>> Using custom FindProxyStubGenerator.cmake from ${CMAKE_CURRENT_LIST_FILE}")

# ---- Locate the generator root -----------------------------------------

if(NOT ProxyStubGenerator_ROOT)
    set(ProxyStubGenerator_ROOT "")

    # 1) If THUNDER_ROOT is set, prefer the installed ConfigGenerator dir
    if(DEFINED ENV{THUNDER_ROOT})
        set(_cand "$ENV{THUNDER_ROOT}/install/include/Thunder/ConfigGenerator")
        if(EXISTS "${_cand}/config_generator.py")
            set(ProxyStubGenerator_ROOT "${_cand}")
        endif()
    endif()

    # 2) Also try CMAKE_PREFIX_PATH/include/Thunder/(ConfigGenerator|ProxyStubGenerator)
    if(NOT ProxyStubGenerator_ROOT AND CMAKE_PREFIX_PATH)
        foreach(_p IN LISTS CMAKE_PREFIX_PATH)
            foreach(_suffix "ConfigGenerator" "ProxyStubGenerator")
                set(_cand "${_p}/include/Thunder/${_suffix}")
                if(EXISTS "${_cand}/config_generator.py")
                    set(ProxyStubGenerator_ROOT "${_cand}")
                endif()
            endforeach()
        endforeach()
    endif()
endif()

include(FindPackageHandleStandardArgs)
find_package_handle_standard_args(
    ProxyStubGenerator
    REQUIRED_VARS ProxyStubGenerator_ROOT
    FAIL_MESSAGE "Could not find ProxyStubGenerator (config_generator.py)"
)

if(ProxyStubGenerator_FOUND)
    message(STATUS "ProxyStubGenerator root: ${ProxyStubGenerator_ROOT}")
endif()

# ---- Define the ProxyStubGenerator() macro used by Thunder + Interfaces --

include(CMakeParseArguments)

function(ProxyStubGenerator)
    # Thunder / ThunderInterfaces use:
    #   ProxyStubGenerator(
    #       NAMESPACE "Thunder::RPC"    (optional)
    #       INPUT <headers...>          (one or many)
    #       OUTDIR <dir>
    #       INCLUDE_PATH <dirs...>      (ignored in stub)
    #   )
    set(options "")
    set(oneValueArgs NAMESPACE OUTDIR)
    set(multiValueArgs INPUT INCLUDE_PATH)
    cmake_parse_arguments(PSG "${options}" "${oneValueArgs}" "${multiValueArgs}" ${ARGN})

    if(NOT PSG_OUTDIR)
        message(FATAL_ERROR "ProxyStubGenerator: OUTDIR is required")
    endif()

    file(MAKE_DIRECTORY "${PSG_OUTDIR}")

    # We don't actually generate real stubs here; just create a dummy file
    # so the build can proceed.
    set(_outfile "${PSG_OUTDIR}/ProxyStubs_Stub.cpp")

    if(NOT EXISTS "${_outfile}")
        message(STATUS "ProxyStubGenerator (stub): creating ${_outfile}")
        file(WRITE "${_outfile}" "
            // Stub proxy stubs for interfaces/COM
            // Generated by local FindProxyStubGenerator.cmake
            // Real builds should use ThunderTools' Python generator.
        ")
    else()
        message(STATUS "ProxyStubGenerator (stub): ${_outfile} already exists")
    endif()
endfunction()

